/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface RichLavatar {
    'alt'?: string;
    'background'?: string;
    'bold'?: boolean;
    'color'?: string;
    'length'?: number;
    'lowercase'?: boolean;
    'name': string;
    'percent'?: number;
    'protocol'?: "http" | "https";
    'rounded'?: boolean;
    'size'?: number;
    'uppercase'?: boolean;
  }
  interface RichLavatarAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'background'?: string;
    'bold'?: boolean;
    'color'?: string;
    'length'?: number;
    'lowercase'?: boolean;
    'name'?: string;
    'percent'?: number;
    'protocol'?: "http" | "https";
    'rounded'?: boolean;
    'size'?: number;
    'uppercase'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'RichLavatar': Components.RichLavatar;
  }

  interface StencilIntrinsicElements {
    'rich-lavatar': Components.RichLavatarAttributes;
  }


  interface HTMLRichLavatarElement extends Components.RichLavatar, HTMLStencilElement {}
  var HTMLRichLavatarElement: {
    prototype: HTMLRichLavatarElement;
    new (): HTMLRichLavatarElement;
  };

  interface HTMLElementTagNameMap {
    'rich-lavatar': HTMLRichLavatarElement
  }

  interface ElementTagNameMap {
    'rich-lavatar': HTMLRichLavatarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
